format_version: "2.0"

meta:
    name: "Super Clever Plan Backend"
    type: "docker"
    slug:  "supercleverplan-backend"
    version: "2.0.0"

config:
    service:
        enabled: false
    cron:
        enabled: true
        entries:
            - time: "*/5 * * * *"
              command: "bash -c 'python3 run.py --teachermap-file /var/plandata/preparsed/teachermap.json --output /var/plandata/out/data.json timetable && chmod +x /app/upload.sh && bash /app/upload.sh'"
              type: "docker"
              docker_container: "supercleverplan"

    storage:
      entries:
          - path: "/var/flying/supercleverplan-backend/preparsed"
          - path: "/var/flying/supercleverplan-backend/out"