format_version: "2.0"

meta:
    name: "Super Clever Plan Backend"
    type: "docker"
    slug:  "supercleverplan-backend"
    version: "2.0.0"

config:
    cron:
        enabled: true
        entries:
            - time: "*/5 * * * *"
              command: "python3 run.py -h"
              type: "docker"
              docker_container: "supercleverplan"

    storage:
      entries:
          - path: "/var/flying/supercleverplan-backend"